name: Deploy React app
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    - uses: actions/checkout@v2
    - name: Build app
      run: |
        npm ci
        npm run build --if-present
        echo "Built!"
